const colors = require("tailwindcss/colors");

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    container: {
      padding: {
        xs: "1rem",
        sm: "1rem",
        lg: "2rem",
        xl: "3rem",
        "2xl": "4rem",
      },
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      spacing: {
        4.25: "1.25rem",
        4.5: "1.5rem",
        13: "3.25rem",
        15: "3.75rem",
        16.5: "4.125rem",
        17: "4.25rem",
        18: "4.5rem",
        19: "4.75rem",
        55: "13.75rem",
        128: "32rem",
        144: "36rem",
      },
      fontFamily: {
        sans: ["Poppins"],
        montserrat: "'Montserrat', sans-serif",
        poppins: "'Poppins', '', sans-serif",
        poppins_bold: ["Poppins-Bold", "sans-serif"],
        poppins_semi_bold: ["Poppins-SemiBold", "sans-serif"],
        poppins_medium: ["Poppins-Medium", "sans-serif"],
        poppins_light: ["Poppins-Light", "sans-serif"],
        sans_serif: "sans-serif",
        sf_pro: "SF Pro Display",
        nebula: "Nebula",
        blank_space: "Blank Space",
      },
    },
    colors: {
      primary: "#02A4FF",
      secondary: "#0FE3E3",
      transparent: "transparent",
      vbDisableText: "#4B5C86",
      vbDisabled: "#232E49",
      vbLine: "#3EE8FF",
      hint: "#7694DE",
      item: "#182844",
      popupVb: "#182233",
      notiSuccess: "#0FE3E3",
      notiWarning: "#FA8C16",
      newForm: "#0D1522",
      itemForm: "#0E1B31",
      balanceVTHO: "#FAAD14",
      grey: {
        1: "#ffffff",
        2: "#FAFAFA",
        3: "#F5F5F5",
        6: "#BFBFBF",
        7: "#8C8C8C",
        9: "#262626",
      },
      black: colors.black,
      white: colors.white,
      gray: colors.neutral,
      indigo: colors.indigo,
      red: colors.red,
      green: colors.green,
      blue: colors.blue,
      pink: colors.pink,
      yellow: colors.yellow,
      "color-modal-wallet": "#182233",
      "color-item-modal-wallet": "#182844",
      "color-item-hover-modal-wallet": "#232E49",
      "tooltip": "#273958",
      assetNetwork: "#678BCA",
    },
    // fontSize: {
    //   xs: ['12px', '16px'],
    //   sm: ['14px', '20px'],
    //   base: ['16px', '24px'],
    //   lg: ['20px', '28px'],
    //   xl: ['24px', '32px'],
    //   '2xl': ['28px', '38px'],
    //   '3xl': ['32px', '40px']
    // }
  },
  plugins: [],
};
